spring.application.name=task-manager
spring.data.mongodb.uri=mongodb+srv://nitish_db_user:nitish%401231@task-manager-cluster.ggcoxrj.mongodb.net/taskdb
spring.data.mongodb.database=taskdb

# JWT Configuration for production
jwt.secret=mysecretkeymysecretkeymysecretkeyforproductiondeployment
jwt.secret.env=production
jwt.secret.render=true
logging.level.org.springframework.security=DEBUG
logging.level.com.nitish.task_manager=DEBUG
server.servlet.context-path=/
